# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'

    - name: Install gcc and graphics libraries
      run: sudo apt-get install -y gcc libgl1-mesa-dev xorg-dev
    - name: Install Fyne
      run: go install fyne.io/fyne/v2/cmd/fyne@latest
    - name: Install UPX
      uses: crazy-max/ghaction-upx@v2
      with:
        install-only: true

    - name: Build
      run: go build -ldflags="-s -H=windowsgui" -o moogle-mod-manager
    
    - name: upx
      run: upx -9 -k moogle-mod-manager
      
    - name: upload to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: moogle-mod-manager
        asset_name: moogle-mod-manager
        tag: latest
        overwrite: true
